### PR TITLE
Add PyLav tags

### PR DESCRIPTION
**Pull request by Drapersniper**
Add two tags,  `core-pylav` and `extra-pylav`; these are direct replacements for the audio tags.

Note: For PyLav to be functional, we need a Python3.11 image - so there is no need to merge this before you update the base image to 3.11, as these images wouldn't work.

Before merging this lets have a chat in discord

### CODE REVIEW

**Comment by Drapersniper** [comment]
While in theory is ready to be used - gonna change change it to a draft until the next release of PyLav - just so we don't merge it and have users struggling too much.

**Comment by greis96** [comment]
LMFA, So I kind of forgot about this PR 😅 

But it is ready for review

**Comment by Drapersniper** [comment]
I kind of forgot about this PR.

It is ready for review

**Comment by PhasecoreX** [comment]
Wow I am garbage at git lol. Sorry this took so long to get to, it looks very good. I didn't mean to merge it quite yet though, as I saw this error when starting the bot, wasn't sure if this was expected:
```
2024-01-06 15:30:30  INFO: PyLav setup and update failed: [Errno 2] No such file or directory: '/data/pylav/.hashfile'
Traceback (most recent call last):
  File "/app/functions/pylav_setup.py", line 264, in <module>
    update_existing_commit(current_commit)
  File "/app/functions/pylav_setup.py", line 231, in update_existing_commit
    with PyLavHashFile.open("w", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/pylav/.hashfile'
```

**Comment by PhasecoreX** [comment]
9b7718e looks like it should fix it. The `/data/pylav` folder wasn't created.

**Comment by Drapersniper** [comment]
Weird I wonder how the fuck I did not hit this before locally 🫠 thanks for fixing!

**Pull request merged**
